const features=[['✦','Swiss Mechanical Movement','A 28,800 vph automatic calibre rendered in layered bridges, ruby jewels, and a gold micro-rotor.'],['◈','Sapphire Crystal','Domed crystal with anti-reflective clarity, crisp edge highlights, and cinematic glass dispersion.'],['◌','Hybrid Intelligence','Discreet notifications, health signals, and travel-time logic hidden beneath a timeless dial.'],['◆','Hand-Finished Materials','Brushed steel, polished gold, ceramic, and leather textures tuned for tactile luxury.']];
const models=['Nocturne 01','Mariner Steel','Chronograph GT','Atelier Gold'];
document.querySelector('#features').innerHTML=features.map(([i,t,d])=>`<article class="card reveal"><div class="icon-orb">${i}</div><h3>${t}</h3><p>${d}</p></article>`).join('');
document.querySelector('#models').innerHTML=models.map((m,i)=>`<article class="model reveal"><span>0${i+1}</span><div class="watch-mini"></div><h3>${m}</h3><p>${['Dress automatic','Diver hybrid','Flyback chronograph','Limited edition'][i]}</p></article>`).join('');
document.querySelectorAll('.strap button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.strap button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelector('.strap span').textContent=`${btn.textContent} strap selected`;}));
const c=document.querySelector('#stage'),ctx=c.getContext('2d');let w,h,dpr;const dust=Array.from({length:180},()=>({x:Math.random(),y:Math.random(),z:Math.random(),r:Math.random()*1.7+.2}));function resize(){dpr=Math.min(devicePixelRatio||1,2);w=c.width=innerWidth*dpr;h=c.height=innerHeight*dpr;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function ring(x,y,r,line,color,blur=0){ctx.save();ctx.shadowColor=color;ctx.shadowBlur=blur;ctx.strokeStyle=color;ctx.lineWidth=line;ctx.beginPath();ctx.ellipse(x,y,r*1.05,r*.96,0,0,Math.PI*2);ctx.stroke();ctx.restore()}function roundedRect(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawWatch(t){const s=scrollY/(document.body.scrollHeight-innerHeight);const cx=innerWidth*(.58-.18*Math.sin(s*Math.PI*1.2)),cy=innerHeight*(.48+.08*Math.cos(s*4));const scale=Math.min(innerWidth,innerHeight)/620*(1+s*.65);const orbit=t*.00016+s*5.4;ctx.save();ctx.translate(cx,cy);ctx.scale(scale,scale);ctx.rotate(Math.sin(orbit)*.16);const explode=Math.max(0,Math.min(1,(s-.36)/.24))-Math.max(0,Math.min(1,(s-.72)/.18));ctx.globalAlpha=.95;roundedRect(-48,-245-explode*70,96,192,32,'#17110d');roundedRect(-48,55+explode*80,96,192,32,'#17110d');for(let i=0;i<16;i++){ctx.fillStyle=`rgba(242,240,235,${.025+i*.003})`;ctx.fillRect(-40+i*5,-230-explode*70,1,170);ctx.fillRect(-40+i*5,70+explode*80,1,170)}ring(0,0,145+explode*20,30,'#8d98a3',16);ring(0,0,126+explode*45,22,'#d4af37',22);const grad=ctx.createRadialGradient(-40,-45,10,0,0,108);grad.addColorStop(0,'#24242a');grad.addColorStop(1,'#030306');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(0,0,112,0,Math.PI*2);ctx.fill();for(let i=0;i<60;i++){const a=i/60*Math.PI*2;ctx.save();ctx.rotate(a);ctx.fillStyle=i%5?'#8d98a3':'#d4af37';ctx.fillRect(-1.5,-98,i%5?3:6,i%5?11:25);ctx.restore()}for(let i=0;i<9;i++){ctx.save();ctx.translate(Math.sin(i*1.7+orbit)*55,Math.cos(i*1.2)*42+explode*55);ctx.rotate(t*.001*(i%2?1:-1));ring(0,0,15+i%3*5,3,i%2?'#d4af37':'#6c8a9f',8);ctx.restore()}ctx.save();ctx.rotate(-.55+t*.00002);roundedRect(-5,-8,10,-64,5,'#d4af37');ctx.restore();ctx.save();ctx.rotate(.72+t*.00008);roundedRect(-3,-8,6,-91,4,'#c8d5dc');ctx.restore();ctx.fillStyle='#d4af37';ctx.beginPath();ctx.arc(0,0,10,0,7);ctx.fill();ctx.globalCompositeOperation='screen';const g=ctx.createLinearGradient(-120,-120,130,130);g.addColorStop(0,'rgba(255,255,255,.38)');g.addColorStop(.4,'rgba(255,255,255,.04)');g.addColorStop(1,'rgba(108,138,159,.08)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,-8,115+explode*100,0,Math.PI*2);ctx.fill();ctx.restore()}
function frame(t){ctx.clearRect(0,0,innerWidth,innerHeight);const bg=ctx.createRadialGradient(innerWidth*.68,innerHeight*.18,0,innerWidth*.5,innerHeight*.45,innerWidth*.9);bg.addColorStop(0,'#263440');bg.addColorStop(.34,'#0b0b0f');bg.addColorStop(1,'#030305');ctx.fillStyle=bg;ctx.fillRect(0,0,innerWidth,innerHeight);ctx.fillStyle='rgba(242,240,235,.35)';dust.forEach(p=>{const y=(p.y*innerHeight+t*.006*(.2+p.z))%innerHeight;ctx.globalAlpha=.08+p.z*.35;ctx.beginPath();ctx.arc(p.x*innerWidth,y,p.r,0,7);ctx.fill()});ctx.globalAlpha=1;drawWatch(t);requestAnimationFrame(frame)}requestAnimationFrame(frame);
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.15});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
